# Generated by Django 5.0.7 on 2024-08-06 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('Did', models.AutoField(primary_key=True, serialize=False)),
                ('Day', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Sid', models.AutoField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=250)),
                ('Phone', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('Aid', models.AutoField(primary_key=True, serialize=False)),
                ('Did', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logic.day')),
                ('Sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Fid', models.AutoField(primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('good', 'good'), ('poor', 'poor')], max_length=10)),
                ('Aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.allocation')),
            ],
        ),
    ]
