# Generated by Django 5.0.7 on 2024-08-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_alter_day_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Aid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='logic.allocation'),
        ),
    ]
