# Generated by Django 5.0.7 on 2024-08-14 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_alter_feedback_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
