# Generated by Django 5.0.7 on 2024-08-17 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='Did',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='logic.day'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='Sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='logic.staff'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Aid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='logic.allocation'),
        ),
    ]
