# Generated by Django 5.0.7 on 2024-08-25 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_alter_allocation_did_alter_allocation_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='Did',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logic.day'),
        ),
    ]
